/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.wur.alterra.cgi.ace.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Measure service. Represents a row in the &quot;Ace_Measure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link nl.wur.alterra.cgi.ace.model.impl.MeasureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link nl.wur.alterra.cgi.ace.model.impl.MeasureImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a measure model instance should use the {@link Measure} interface instead.
 * </p>
 *
 * @author groot052
 * @see Measure
 * @see nl.wur.alterra.cgi.ace.model.impl.MeasureImpl
 * @see nl.wur.alterra.cgi.ace.model.impl.MeasureModelImpl
 * @generated
 */
public interface MeasureModel extends BaseModel<Measure> {
	/**
	 * Gets the primary key of this measure.
	 *
	 * @return the primary key of this measure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this measure
	 *
	 * @param pk the primary key of this measure
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the measure id of this measure.
	 *
	 * @return the measure id of this measure
	 */
	public long getMeasureId();

	/**
	 * Sets the measure id of this measure.
	 *
	 * @param measureId the measure id of this measure
	 */
	public void setMeasureId(long measureId);

	/**
	 * Gets the company id of this measure.
	 *
	 * @return the company id of this measure
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this measure.
	 *
	 * @param companyId the company id of this measure
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this measure.
	 *
	 * @return the group id of this measure
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this measure.
	 *
	 * @param groupId the group id of this measure
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the name of this measure.
	 *
	 * @return the name of this measure
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this measure.
	 *
	 * @param name the name of this measure
	 */
	public void setName(String name);

	/**
	 * Gets the description of this measure.
	 *
	 * @return the description of this measure
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this measure.
	 *
	 * @param description the description of this measure
	 */
	public void setDescription(String description);

	/**
	 * Gets the implementationtype of this measure.
	 *
	 * @return the implementationtype of this measure
	 */
	@AutoEscape
	public String getImplementationtype();

	/**
	 * Sets the implementationtype of this measure.
	 *
	 * @param implementationtype the implementationtype of this measure
	 */
	public void setImplementationtype(String implementationtype);

	/**
	 * Gets the implementationtime of this measure.
	 *
	 * @return the implementationtime of this measure
	 */
	public long getImplementationtime();

	/**
	 * Sets the implementationtime of this measure.
	 *
	 * @param implementationtime the implementationtime of this measure
	 */
	public void setImplementationtime(long implementationtime);

	/**
	 * Gets the lifetime of this measure.
	 *
	 * @return the lifetime of this measure
	 */
	public long getLifetime();

	/**
	 * Sets the lifetime of this measure.
	 *
	 * @param lifetime the lifetime of this measure
	 */
	public void setLifetime(long lifetime);

	/**
	 * Gets the spatiallayer of this measure.
	 *
	 * @return the spatiallayer of this measure
	 */
	@AutoEscape
	public String getSpatiallayer();

	/**
	 * Sets the spatiallayer of this measure.
	 *
	 * @param spatiallayer the spatiallayer of this measure
	 */
	public void setSpatiallayer(String spatiallayer);

	/**
	 * Gets the spatialvalues of this measure.
	 *
	 * @return the spatialvalues of this measure
	 */
	@AutoEscape
	public String getSpatialvalues();

	/**
	 * Sets the spatialvalues of this measure.
	 *
	 * @param spatialvalues the spatialvalues of this measure
	 */
	public void setSpatialvalues(String spatialvalues);

	/**
	 * Gets the legalaspects of this measure.
	 *
	 * @return the legalaspects of this measure
	 */
	@AutoEscape
	public String getLegalaspects();

	/**
	 * Sets the legalaspects of this measure.
	 *
	 * @param legalaspects the legalaspects of this measure
	 */
	public void setLegalaspects(String legalaspects);

	/**
	 * Gets the stakeholderparticipation of this measure.
	 *
	 * @return the stakeholderparticipation of this measure
	 */
	@AutoEscape
	public String getStakeholderparticipation();

	/**
	 * Sets the stakeholderparticipation of this measure.
	 *
	 * @param stakeholderparticipation the stakeholderparticipation of this measure
	 */
	public void setStakeholderparticipation(String stakeholderparticipation);

	/**
	 * Gets the contact of this measure.
	 *
	 * @return the contact of this measure
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this measure.
	 *
	 * @param contact the contact of this measure
	 */
	public void setContact(String contact);

	/**
	 * Gets the succeslimitations of this measure.
	 *
	 * @return the succeslimitations of this measure
	 */
	@AutoEscape
	public String getSucceslimitations();

	/**
	 * Sets the succeslimitations of this measure.
	 *
	 * @param succeslimitations the succeslimitations of this measure
	 */
	public void setSucceslimitations(String succeslimitations);

	/**
	 * Gets the website of this measure.
	 *
	 * @return the website of this measure
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this measure.
	 *
	 * @param website the website of this measure
	 */
	public void setWebsite(String website);

	/**
	 * Gets the costbenefit of this measure.
	 *
	 * @return the costbenefit of this measure
	 */
	@AutoEscape
	public String getCostbenefit();

	/**
	 * Sets the costbenefit of this measure.
	 *
	 * @param costbenefit the costbenefit of this measure
	 */
	public void setCostbenefit(String costbenefit);

	/**
	 * Gets the keywords of this measure.
	 *
	 * @return the keywords of this measure
	 */
	@AutoEscape
	public String getKeywords();

	/**
	 * Sets the keywords of this measure.
	 *
	 * @param keywords the keywords of this measure
	 */
	public void setKeywords(String keywords);

	/**
	 * Gets the startdate of this measure.
	 *
	 * @return the startdate of this measure
	 */
	public Date getStartdate();

	/**
	 * Sets the startdate of this measure.
	 *
	 * @param startdate the startdate of this measure
	 */
	public void setStartdate(Date startdate);

	/**
	 * Gets the enddate of this measure.
	 *
	 * @return the enddate of this measure
	 */
	public Date getEnddate();

	/**
	 * Sets the enddate of this measure.
	 *
	 * @param enddate the enddate of this measure
	 */
	public void setEnddate(Date enddate);

	/**
	 * Gets the publicationdate of this measure.
	 *
	 * @return the publicationdate of this measure
	 */
	public Date getPublicationdate();

	/**
	 * Sets the publicationdate of this measure.
	 *
	 * @param publicationdate the publicationdate of this measure
	 */
	public void setPublicationdate(Date publicationdate);

	/**
	 * Gets the language of this measure.
	 *
	 * @return the language of this measure
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this measure.
	 *
	 * @param language the language of this measure
	 */
	public void setLanguage(String language);

	/**
	 * Gets the sectors_ of this measure.
	 *
	 * @return the sectors_ of this measure
	 */
	@AutoEscape
	public String getSectors_();

	/**
	 * Sets the sectors_ of this measure.
	 *
	 * @param sectors_ the sectors_ of this measure
	 */
	public void setSectors_(String sectors_);

	/**
	 * Gets the elements_ of this measure.
	 *
	 * @return the elements_ of this measure
	 */
	@AutoEscape
	public String getElements_();

	/**
	 * Sets the elements_ of this measure.
	 *
	 * @param elements_ the elements_ of this measure
	 */
	public void setElements_(String elements_);

	/**
	 * Gets the climateimpacts_ of this measure.
	 *
	 * @return the climateimpacts_ of this measure
	 */
	@AutoEscape
	public String getClimateimpacts_();

	/**
	 * Sets the climateimpacts_ of this measure.
	 *
	 * @param climateimpacts_ the climateimpacts_ of this measure
	 */
	public void setClimateimpacts_(String climateimpacts_);

	/**
	 * Gets the mao_type of this measure.
	 *
	 * @return the mao_type of this measure
	 */
	@AutoEscape
	public String getMao_type();

	/**
	 * Sets the mao_type of this measure.
	 *
	 * @param mao_type the mao_type of this measure
	 */
	public void setMao_type(String mao_type);

	/**
	 * Gets a copy of this measure as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Measure toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Measure measure);

	public int hashCode();

	public String toString();

	public String toXmlString();
}