/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.wur.alterra.cgi.ace.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AceItem service. Represents a row in the &quot;Ace_AceItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link nl.wur.alterra.cgi.ace.model.impl.AceItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link nl.wur.alterra.cgi.ace.model.impl.AceItemImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a ace item model instance should use the {@link AceItem} interface instead.
 * </p>
 *
 * @author groot052
 * @see AceItem
 * @see nl.wur.alterra.cgi.ace.model.impl.AceItemImpl
 * @see nl.wur.alterra.cgi.ace.model.impl.AceItemModelImpl
 * @generated
 */
public interface AceItemModel extends BaseModel<AceItem> {
	/**
	 * Gets the primary key of this ace item.
	 *
	 * @return the primary key of this ace item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ace item
	 *
	 * @param pk the primary key of this ace item
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the ace item id of this ace item.
	 *
	 * @return the ace item id of this ace item
	 */
	public long getAceItemId();

	/**
	 * Sets the ace item id of this ace item.
	 *
	 * @param aceItemId the ace item id of this ace item
	 */
	public void setAceItemId(long aceItemId);

	/**
	 * Gets the company id of this ace item.
	 *
	 * @return the company id of this ace item
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this ace item.
	 *
	 * @param companyId the company id of this ace item
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this ace item.
	 *
	 * @return the group id of this ace item
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this ace item.
	 *
	 * @param groupId the group id of this ace item
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the name of this ace item.
	 *
	 * @return the name of this ace item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ace item.
	 *
	 * @param name the name of this ace item
	 */
	public void setName(String name);

	/**
	 * Gets the description of this ace item.
	 *
	 * @return the description of this ace item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ace item.
	 *
	 * @param description the description of this ace item
	 */
	public void setDescription(String description);

	/**
	 * Gets the type of this ace item.
	 *
	 * @return the type of this ace item
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this ace item.
	 *
	 * @param type the type of this ace item
	 */
	public void setType(String type);

	/**
	 * Gets the stored at of this ace item.
	 *
	 * @return the stored at of this ace item
	 */
	@AutoEscape
	public String getStoredAt();

	/**
	 * Sets the stored at of this ace item.
	 *
	 * @param storedAt the stored at of this ace item
	 */
	public void setStoredAt(String storedAt);

	/**
	 * Gets the sector of this ace item.
	 *
	 * @return the sector of this ace item
	 */
	@AutoEscape
	public String getSector();

	/**
	 * Sets the sector of this ace item.
	 *
	 * @param sector the sector of this ace item
	 */
	public void setSector(String sector);

	/**
	 * Gets the pilar of this ace item.
	 *
	 * @return the pilar of this ace item
	 */
	@AutoEscape
	public String getPilar();

	/**
	 * Sets the pilar of this ace item.
	 *
	 * @param pilar the pilar of this ace item
	 */
	public void setPilar(String pilar);

	/**
	 * Gets the text search of this ace item.
	 *
	 * @return the text search of this ace item
	 */
	@AutoEscape
	public String getTextSearch();

	/**
	 * Sets the text search of this ace item.
	 *
	 * @param textSearch the text search of this ace item
	 */
	public void setTextSearch(String textSearch);

	/**
	 * Gets the keyword of this ace item.
	 *
	 * @return the keyword of this ace item
	 */
	@AutoEscape
	public String getKeyword();

	/**
	 * Sets the keyword of this ace item.
	 *
	 * @param keyword the keyword of this ace item
	 */
	public void setKeyword(String keyword);

	/**
	 * Gets the nuts id of this ace item.
	 *
	 * @return the nuts id of this ace item
	 */
	@AutoEscape
	public String getNutsId();

	/**
	 * Sets the nuts id of this ace item.
	 *
	 * @param nutsId the nuts id of this ace item
	 */
	public void setNutsId(String nutsId);

	/**
	 * Gets the nuts level of this ace item.
	 *
	 * @return the nuts level of this ace item
	 */
	@AutoEscape
	public String getNutsLevel();

	/**
	 * Sets the nuts level of this ace item.
	 *
	 * @param nutsLevel the nuts level of this ace item
	 */
	public void setNutsLevel(String nutsLevel);

	/**
	 * Gets the start date of this ace item.
	 *
	 * @return the start date of this ace item
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this ace item.
	 *
	 * @param startDate the start date of this ace item
	 */
	public void setStartDate(Date startDate);

	/**
	 * Gets the end date of this ace item.
	 *
	 * @return the end date of this ace item
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this ace item.
	 *
	 * @param endDate the end date of this ace item
	 */
	public void setEndDate(Date endDate);

	/**
	 * Gets a copy of this ace item as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public AceItem toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AceItem aceItem);

	public int hashCode();

	public String toString();

	public String toXmlString();
}