package nl.wur.alterra.cgi.ace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WxsHarvester service. Represents a row in the &quot;Ace_WxsHarvester&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link nl.wur.alterra.cgi.ace.model.impl.WxsHarvesterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link nl.wur.alterra.cgi.ace.model.impl.WxsHarvesterImpl}.
 * </p>
 *
 * @author groot052
 * @see WxsHarvester
 * @see nl.wur.alterra.cgi.ace.model.impl.WxsHarvesterImpl
 * @see nl.wur.alterra.cgi.ace.model.impl.WxsHarvesterModelImpl
 * @generated
 */
public interface WxsHarvesterModel extends BaseModel<WxsHarvester> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a wxs harvester model instance should use the {@link WxsHarvester} interface instead.
     */

    /**
     * Returns the primary key of this wxs harvester.
     *
     * @return the primary key of this wxs harvester
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this wxs harvester.
     *
     * @param primaryKey the primary key of this wxs harvester
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the wxsharvesterid of this wxs harvester.
     *
     * @return the wxsharvesterid of this wxs harvester
     */
    public long getWxsharvesterid();

    /**
     * Sets the wxsharvesterid of this wxs harvester.
     *
     * @param wxsharvesterid the wxsharvesterid of this wxs harvester
     */
    public void setWxsharvesterid(long wxsharvesterid);

    /**
     * Returns the name of this wxs harvester.
     *
     * @return the name of this wxs harvester
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this wxs harvester.
     *
     * @param name the name of this wxs harvester
     */
    public void setName(String name);

    /**
     * Returns the url of this wxs harvester.
     *
     * @return the url of this wxs harvester
     */
    @AutoEscape
    public String getUrl();

    /**
     * Sets the url of this wxs harvester.
     *
     * @param url the url of this wxs harvester
     */
    public void setUrl(String url);

    /**
     * Returns the ogctype of this wxs harvester.
     *
     * @return the ogctype of this wxs harvester
     */
    @AutoEscape
    public String getOgctype();

    /**
     * Sets the ogctype of this wxs harvester.
     *
     * @param ogctype the ogctype of this wxs harvester
     */
    public void setOgctype(String ogctype);

    /**
     * Returns the every of this wxs harvester.
     *
     * @return the every of this wxs harvester
     */
    public int getEvery();

    /**
     * Sets the every of this wxs harvester.
     *
     * @param every the every of this wxs harvester
     */
    public void setEvery(int every);

    /**
     * Returns the topic of this wxs harvester.
     *
     * @return the topic of this wxs harvester
     */
    @AutoEscape
    public String getTopic();

    /**
     * Sets the topic of this wxs harvester.
     *
     * @param topic the topic of this wxs harvester
     */
    public void setTopic(String topic);

    /**
     * Returns the status of this wxs harvester.
     *
     * @return the status of this wxs harvester
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this wxs harvester.
     *
     * @param status the status of this wxs harvester
     */
    public void setStatus(String status);

    /**
     * Returns the saved to geo network of this wxs harvester.
     *
     * @return the saved to geo network of this wxs harvester
     */
    public boolean getSavedToGeoNetwork();

    /**
     * Returns <code>true</code> if this wxs harvester is saved to geo network.
     *
     * @return <code>true</code> if this wxs harvester is saved to geo network; <code>false</code> otherwise
     */
    public boolean isSavedToGeoNetwork();

    /**
     * Sets whether this wxs harvester is saved to geo network.
     *
     * @param savedToGeoNetwork the saved to geo network of this wxs harvester
     */
    public void setSavedToGeoNetwork(boolean savedToGeoNetwork);

    /**
     * Returns the geonetwork ID of this wxs harvester.
     *
     * @return the geonetwork ID of this wxs harvester
     */
    public long getGeonetworkId();

    /**
     * Sets the geonetwork ID of this wxs harvester.
     *
     * @param geonetworkId the geonetwork ID of this wxs harvester
     */
    public void setGeonetworkId(long geonetworkId);

    /**
     * Returns the geonetwork u u i d of this wxs harvester.
     *
     * @return the geonetwork u u i d of this wxs harvester
     */
    @AutoEscape
    public String getGeonetworkUUID();

    /**
     * Sets the geonetwork u u i d of this wxs harvester.
     *
     * @param geonetworkUUID the geonetwork u u i d of this wxs harvester
     */
    public void setGeonetworkUUID(String geonetworkUUID);

    /**
     * Returns the company ID of this wxs harvester.
     *
     * @return the company ID of this wxs harvester
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this wxs harvester.
     *
     * @param companyId the company ID of this wxs harvester
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this wxs harvester.
     *
     * @return the group ID of this wxs harvester
     */
    public long getGroupId();

    /**
     * Sets the group ID of this wxs harvester.
     *
     * @param groupId the group ID of this wxs harvester
     */
    public void setGroupId(long groupId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(WxsHarvester wxsHarvester);

    @Override
    public int hashCode();

    @Override
    public CacheModel<WxsHarvester> toCacheModel();

    @Override
    public WxsHarvester toEscapedModel();

    @Override
    public WxsHarvester toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
