--
-- PostgreSQL database dump
--

-- Started on 2011-04-06 12:56:36

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- TOC entry 2497 (class 0 OID 28169)
-- Dependencies: 2208
-- Data for Name: ace_measure; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (126, 1, 18, 'Hesketh Out Marsh', 'Hesketh Out Marsh is the biggest managed realignment project in the country. The marsh lies on the southern shore of the River Ribble estuary, near Preston, and is one of the country’s most important estuary habitats for birdlife. Before 2006 Hesketh Out Marsh was used for growing crops. The land was taken out of the estuary in 1980 by the creation of an outer wall, but this wall was never going to last for ever. With the climate changing and the sea level rising, the Royal Society for the Protection of Birds and the Environment Agency recognised the need to plan for the future and create stronger sea defences. At the same timeit was need to create new saltmarsh habitat to replace losses elsewhere.  The new reserve does both these things by the process known as ''managed realignment'' and is one of the largest of its kind in the UK. Seawater is let back in to flood some of the land, creating saltmarsh which provides more space for nature. At the same time, the new saltmarsh acts like a sponge, soaking up some of the energy of the sea before it reaches the strong, new sea defences. By working in partnership with the Environment Agency and with funding from Lancaster City Council, and the Lancashire Rural Recovery Action Plan, the Hesketh Out Marsh project has greatly improved the local sea defences and created 150 hectares of new saltmarsh, creeks and lagoons. Further funding from Biffaward and Natural England has enabled to provide facilities for visitors and for the cows and sheep that graze the marshes as well as funding research into the many changes that are taking place at this exciting new reserve as it returns to the wild.', '', 0, 0, '', '', '', '', '', '', 'http://www.rspb.org.uk/reserves/guide/h/heskethoutmarsh/about.aspx', '', '', NULL, NULL, NULL, '', 'B', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (127, 1, 18, 'Urban Farming', 'More than 80 groups, including primary and secondary schools, pre-school groups (Sure Start), residential homes, allotment associations, mental health units in local hospitals, residents’ groups, voluntary organisations and even the staff of a smart department store in a main shopping street in the town participate in a ‘soil to table’ project devoted to finding a healthier, more sustainable local food system. The groups identified locations in which to grow food and the produce they would like to cultivate. Then, in May 2007, about 1,000 people began growing fruit and vegetables in containers at locations across the town. They received support from local horticulturalists, allotment growers, farmers and food producers. The local council chipped in by agreeing to dig up part of the main local park so the Urban Farming teams could grow specialist plants and food there.', '', 0, 0, 'City', '', '', '', '', '', 'http://www.dott07.com/go/food/urban-farming', '', 'adaptation action', NULL, NULL, NULL, 'E', 'A', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (101, 1, 18, 'Bournemouth Beach, Poole Bay, UK', 'Poole Bay, located on the south coast of England, has undergone periodic re-nourishment from the
1970s to the present day. To date, three large-scale nourishment projects have been undertaken during
the periods 1974-1975, 1988-1990 and 2005-2009. These nourishments have helped to maintain a wide, sandy beach which is important to the tourist economy of the area. The nourishment activities, coupled with regular and systematic monitoring, provide a best practice case study of beach nourishment.The decision to employ nourishment at this site was taken following a period of damage to hard defences such as seawalls and groynes in the 1960s. These hard protection measures had achieved limited success in retaining beach material. Nourishment was selected to address these problems and because it was seen as beneficial to the area’s tourist economy, generated largely due to the presence of golden, sandy beaches.', '', 0, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', '', '', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (102, 1, 18, 'Beach Nourishment; Bournemouth Beach, Poole Bay, UK', 'Poole Bay, located on the south coast of England, has undergone periodic re-nourishment from the
1970s to the present day. To date, three large-scale nourishment projects have been undertaken during
the periods 1974-1975, 1988-1990 and 2005-2009. These nourishments have helped to maintain a wide, sandy beach which is important to the tourist economy of the area. The nourishment activities, coupled with regular and systematic monitoring, provide a best practice case study of beach nourishment.The decision to employ nourishment at this site was taken following a period of damage to hard defences such as seawalls and groynes in the 1960s. These hard protection measures had achieved limited success in retaining beach material. Nourishment was selected to address these problems and because it was seen as beneficial to the area’s tourist economy, generated largely due to the presence of golden, sandy beaches.', '', 0, 0, '', '', '', '', '', '', 'www.channelcoast.org', '', 'beach nourishment', NULL, NULL, NULL, 'E', 'C', 'M', 'F; S', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (103, 1, 18, 'Sand Dunes; Avalon, New Jersey, USA', 'The dune management programme started with two activities: (1) building dunes along the entire seafront,
using sand fences and vegetation planting; and (2) raising money to buy undeveloped shorefront lots to
create an undeveloped segment of coastline which provides space for landforms to evolve naturally, a
source of sand for replenishing critically eroding areas and a location for experimenting with environmentally
compatible management strategies. It also prevented further development from taking place in the hazard
zone. Another aspect of the management strategy authorised land owners to plant dune vegetation to
initiate natural dune building processes.
Although the dune construction programme encountered early resistance because of the associated
costs, restricted beach access and restricted views, this was overcome by raising awareness of the
effectiveness of dunes as a means of coastal protection. As the programme progressed, it was even
possible to gradually increase dune height and volume in line with advice from organisations experienced
in flood engineering: the US Army Corps of Engineers (USACE) and the Federal Emergency Management
Association (FEMA). Dune strengthening has been supplemented by repetitive beach nourishment using
sediments from a nearby tidal inlet.', '', 0, 0, '', '', '', '', '', '', 'http://www.twobays.net/poole_bay.htm', '', 'sand dunes; coastal protection', NULL, NULL, NULL, 'E', 'C; D', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (104, 1, 18, 'Seawalls; Bar Beach, Victoria Island, Nigeria', 'The main feature was a 1 km long seawall, constructed of large x-shaped, pre-cast concrete elements and designed to interlock and dissipate wave energy upon impact. The top of the seawall is 4 m above MSL (Chagoury Group, 2006) and the blocks are designed to withstand the impact of numerically modelled waves with a return period of 100 years (HiTech, 2006).
The seawall is coupled with other coastal engineering measures in order to provide the most effective
solution to the area’s coastal erosion problems. Further beach nourishment was carried out and additional
rock armour was also placed on the beach. The crest of the seawall was capped with a 10 m wide
concrete slab (HiTech, 2006). This provides the area with a promenade that can be used for recreational
purposes. 
Bar Beach was battered by strong storms during July 2007 and the structure provided adequate protection
against flooding and erosion. However, areas without protection were still hit hard by the storms. As such,
extension of the seawall for a further 500 m is currently under consideration.', '', 0, 0, '', '', '', '', '', '', '', '', 'Coastal protection; sea wall', NULL, NULL, NULL, 'E', 'D; C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (105, 1, 18, 'Sea Dikes; Nam Dinh Province, Vietnam', 'Nam Dinh’s coastline is subject to severe erosion and storm surges. As such, the dike system has two
main functions: (1) flood defence and (2) protecting the inland from erosion (Mai, 2004). It is important
to prevent these processes because erosion reduces available agricultural land while flooding and defence overtopping poses a risk to human life and causes saltwater intrusion which reduces agricultural
productivity. Furthermore, the constant risk of flooding discourages farmers from adopting new technology
or to invest in other income-generating activities (Mai, 2004).
The Vietnamese government has set up a huge sea dikes programme with
two important tasks:
1. Research safety standards, boundary conditions and find optimal solutions for sea defences for the
whole country
2. Design and construct new dikes at places where dikes have not existed before, or have been
breached. This includes reinforcement of existing dikes based on the findings of task 1', '', 0, 0, '', '', '', '', '', '', '', '', 'Sea dikes', NULL, NULL, NULL, '', 'D; C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (106, 1, 18, 'Closure dam; Chaka Maya Closure Dam, Bangladesh', 'Chaka Maya is located in the south-western district of Patuakhali, in Bangladesh. During the period 1978-
79, a closure dam was constructed across a tidal channel of the Andharmanik River, primarily for flood
control purposes. The following project information is taken from DHV Haskoning (2007).
The channel in which the dam was constructed is 210 m wide with an average depth of 5.5 m below MWL.
Due to the size and depth of the channel, traditional methods could not be used. Instead, the dam was
constructed using traditional Dutch methods, as recommended by an experienced, international coastal
engineering consultancy. This method involved the use of readily available, local materials and manual
labour, to gradually close the channel by building up the barrier, layer by layer, from the seabed.
This earth-filled dam was designed with sufficient cross-section and crest height to
withstand the water levels and wave climate associated with the statistically modelled 1 in 20 year storm
return period.
The final cost of the project in 1979, was US$500,000 and required 180,000 man days of employment to
complete; this labour was obtained from the local communities. When adjusted for inflation, the cost of this
project is roughly equivalent to US$1.3 million at 2009 price levels.', '', 0, 0, '', '', '', '', '', '', '', '', 'closure dam; adaptation action', NULL, NULL, NULL, '', 'D; F', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (107, 1, 18, 'The National Flood Insurance Programme, USA', 'The NFIP provides federally guaranteed flood insurance to communities that agree to regulate development in the mapped floodplains. If communities do their part in ensuring that future floodplain development meets certain criteria, FEMA (the Federal Emergency Management Association) will provide flood insurance for properties in the community.
The NFIP requires that all new non-residential developments within a flood hazard area are either elevated
above the floodplain or are flood-proofed. Residential buildings must be elevated above the base flood
elevation. Flood-proofing measures described in Figure 4.21 and Figure 4.22 are taken from FEMA
publications in line with the NFIP.
For the purposes of regulating new construction, NFIP defines flood-proofing as measures incorporated
into the design of the building so that below base flood elevation:
• Walls are watertight
• Structural components can resist hydrostatic and hydrodynamic10 loads, as well as buoyancy effects
• Utilities are protected from flood damage
Under these regulations, a registered professional engineer or architect is required to prepare building
plans and certify flood-proofing measures (FEMA, 1998). The minimum requirement of flood-proofing
under NFIP is to provide protection up to the 1 in 100 year flood.', '', 0, 0, '', '', '', '', '', '', '', '', 'Adaptation action', NULL, NULL, NULL, '', 'D; C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (108, 1, 18, 'Mangrove Afforestation, Bangladesh', 'The coastal areas of Bangladesh have a high frequency of cyclones and historic events have caused
significant damage, high death tolls and significant numbers of casualties.
It was realised that mangrove forests in the Sundarbans, in the south-west of Bangladesh, protected the
local costs from cyclone damage. Therefore in 1966 a programme of mangrove planting was initiated on
the seaward sides of protective embankments in the coastal districts of Patuakhali, Barisal, Noakhali and
Chittagong. The following information is taken from Saenger and Siddiqi (1993).
The initial objective of the afforestation programme was to create a shelter belt to protect the lives and
properties of coastal communities. The early success of these plantations resulted in the setting of
additional objectives which included: (a) providing forest products for a range of uses; (b) developing forest
shelter belts to protect inland life and property from tidal surges; (c) producing resources such as timber
into the national economy; (d) creating employment opportunities in rural communities; and (e) providing
an environment for wildlife.
By 1990, approximately 1200 km2 of mangroves had been planted, with funding support from the World
Bank. To complement the accelerated planting scheme, a more systematic investigation of techniques
was initiated, to refine seedling nursery and planting methods. The organisation responsible for this activity
also identified the need for a management-oriented research programme to deal with pest outbreaks, the
development of thinning schedules, pilot planting, etc.', '', 0, 0, '', '', '', '', '', '', '', '', 'adaptation action; wetlands', NULL, NULL, NULL, '', 'D; C', 'M', 'S', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (109, 1, 18, 'Chandra, Bangladesh Floating Agriculture Scheme', 'Chandra is located in the southwest of Bangladesh on the banks of the River Kabodak. The annual
floods deposited silt onto agricultural land, making it fertile and suitable for agricultural activities.
Over time however, the floods became a nuisance rather than a blessing and in the 1960s, the Coastal Embankment project to reclaim seasonally flooded wetlands for permanent agriculture was implemented. 
Villagers were supplied by the supporting agencies, with training and technical support on the methods of
floating agriculture. Prior to this, villagers were unaware of the technique, despite its prevalence in other
areas of the country. The people of Chandra currently grow 23 types of vegetable and five spices through floating agriculture. The project ran from 2003-2005 and following its success, a second phase was started in the Jessore District of Bangladesh. Although the project only lasted a short time, immediate results were observed. Farmers were able to produce and sell goods out of season, for high returns. When Cyclone Sidr passed through the area, participating farmers observed no negative effects on their vegetable and spice growth and were also able to sell produce for a higher price (LEISA, 2009). This has obvious benefits for adapting to a stormier climate as a result of climate change.', '', 0, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', 'D; C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (110, 1, 18, 'Flood Hazard Mapping; Montego Bay, Jamaica', 'Between 1994 and 1997, the Caribbean Disaster Mitigation Project (CDMP) undertook three storm hazard
assessments in Montego Bay, Jamaica. The purpose of these assessments was to produce maps of
hurricane storm surge hazards for use in emergency management and land development planning in
Montego Bay. The following case study is taken from Smith Warner International (1999).
The flood hazard mapping study was undertaken by CDMP, a joint effort of the Organization of American
States (OAS) and the US Agency for International Development (USAID). The CDMP itself, was initiated
in response to a dramatic increase in the level of destruction caused by hurricanes and tropical storms in
the Caribbean.', '', 0, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', 'D; C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (111, 1, 18, 'Cyclone Warning System, Bangladesh', 'Tropical cyclones in Bangladesh have historically been associated with high death and casualty rates
but because of the country’s low per capita income, capital intensive preventative measures to prevent
or avoid hazard loss were unfeasible (Haque, 1995). As a result, Bangladesh decided to implement the
Cyclone Preparedness Programme (CPP). The CPP activities are centred on three infrastructures: the
cyclone early warning system, public cyclone shelters for pre-disaster evacuation and shelters for cattle
during storm surges (Paul, 2009).
As already stated, warning systems consist of three interconnected phases; (1) evaluation, (2) dissemination/
warning and (3) response. The Bangladesh flood warning procedure also consists of these stages, with the
involvement of multiple bodies and a constant flow of information between them.', '', 0, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', 'D', 'M', 'S', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (112, 1, 18, 'Managed Realignment; Abbotts Hall Farm, Essex, UK', 'In 2002, a managed realignment scheme was undertaken at Abbotts Hall Farm in Essex, UK. The site had
a total area of 0.84 km2 and had been protected from inundation by seawalls for more than 200 years
(ABPMER, 2010b).
Managed realignment was pursued at the site with the primary objectives of flood defence cost reduction
and intertidal and coastal habitat creation. These objectives were selected because the existing seawall
was in a poor state of repair and because in the UK, coastal habitats are in decline.
Monitoring was carried out by the Environment Agency, English Nature and the Essex Wildlife Trust for
three years prior to implementation. This helped ensure that the scheme design would achieve the desired
results. Monitoring also provided a baseline for evaluating the effects of the project. Following realignment,
a further five year monitoring programme was undertaken to assess the effects and provide information to
aid the design of future schemes
Realignment was conducted by creating five breaches in some 3 km of hard defences. The largest breach
was 100 m wide with a level at approximately MHWN. The four remaining breaches were smaller in size, at
10-20 m width and higher levels (ABPMER, 2010a). No new defences were created as the naturally higher
ground behind provided an adequate secondary defence (Environment Agency, 2003). It was necessary
12 The study of fluids in motion.
13 Regulated tidal exchange involves the use of pipes, culverts or sluice gates to allow regular tidal flushing and thus facilitates the
creation of saline or brackish habitats behind sea walls (Sharpe et al., 2002).
109
to construct counter walls however, to prevent flooding of neighbouring land (Essex Wildlife Trust, 2010).
A new creek system was also excavated to encourage saltmarsh formation (Essex Wildlife Trust, 2003).', '', 0, 0, '', '', '', 'The final cost of the project was US$7.7 million (at 2009 price levels) and was funded by the World Wildlife
Fund (WWF) and the English Heritage Lottery Fund.', '', '', '', 'The scheme has been considered a success as the objectives of flood defence, cost reduction and coastal habitat creation were all realised and confirmed by monitoring results. The length of flood defences at the site were reduced by 87% and approximately 0.4 km2 of saltmarsh, 0.35 km2 of coastal grassland and 0.09 km2 of mudflat have been created. In addition, large numbers of birds and fish now living in the area indicate that the habitat has been successfully created.', '', NULL, NULL, NULL, '', 'C; D', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (113, 1, 18, 'Coastal setback; Barbados, Caribbean Islands', 'Two setback distances are used on the island. Along sandy beaches, buildings are required to be a
minimum of 30 m from the Mean High Water Mark (MHWM). In the case of development on coastal cliffs,
there is a minimum setback distance of 10 m from the cliff edge. When the cliff is cantilevered, the setback
is measured from the most landward location of the undercut portion of the cliff, not from the cliff edge.
In some special cases, these setbacks can be increased when rare, threatened or endangered ecosystems,
or important historical or archaeological sites exist. Such features may include mangroves or turtle nesting
sites, to name but two. Conversely, decreases in the setback extent may occur where there are existing
buildings already within the exclusion zone', '', 0, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', 'C; D', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (114, 1, 18, 'Henry Box, Witney, Oxfordshire', 'Flood Proofing and management of development run-off:
The housing development at Henry Box, Witney consists of 92 affordable homes built on 1.1 hectares on a virtually flat site within the floodplain. The water table at this site is only 400-700 mm below ground level and the shallow gradient means innovative measures are required to ensure that there is no increase in flood risk.
The use of either traditional ‘hard’ or sustainable ‘soft’ surface water drainage systems was impractical at this site. The solution was to link, or combine, the hard and soft drainage systems. A combined kerb drain which removed water quickly via inlets into a kerb drainage system every 250 mm was used alongside more sustainable methods such as on site storage (attenuation systems), swales and filter beds.', '', 2001, 0, '', '', '', '', '', '', 'www.constructingexcellence.org.uk; www.acodrain.co.uk', '', 'adaptation action, housing', NULL, NULL, NULL, 'E', 'I', 'M', 'W', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (115, 1, 18, 'Howbery Park, Wallingford, Oxfordshire', 'Management of development run-off and responding to pressures on water resources:
The owners of Howbery Park had planning permission to redevelop the site as a business/science park and construct 11,750 sqm of new office space. The building incorporates a range of environmental and energy saving features, which include a rainwater harvesting system that will collect rainwater from the roof for re-use within the building for toilet flushing. This should satisfy about 40% of the total demand for water. The car park serving the office will also allow rainwater to soak through into the ground, whilst other non-permeable areas will drain into a reed bed. The building also used photo-voltaic cells to generate electrical power which generated approximately 20% of the estimated demand of the building for electrical power. Solar panels installed on the roof will satisfy about 40% of the demand for hot water, and roof mounted, wind-powered turbines will be installed nn the roof to help draw air through the windows and the upper floor of the building.', '', 0, 0, '', '', '', '', '', '', '', '', 'adaptation action, construction', NULL, NULL, NULL, '', 'I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (116, 1, 18, 'Alpine Close, Greenfields, Maidenhead, Berkshire', 'Management of development run-off and responding to pressures on water resources:
The Alpine Close, Greenfields Scheme is an affordable housing development completed in 2001.
The scheme is designed to reduce the natural resource use and energy consumption in the construction process and for daily living. The houses will use up to 50% less energy and 30% less water than a conventional house. The roofs are planted with chives, saxifrage and sedum, which are all tough flowering alpine plants which will help reduce excess water runoff by 90% and which act as a mini-habitat for wildlife. The roof offers extra protection to the waterproofing layer and can extend the roof’s lifetime by a factor of up to four. The roof will require annual maintenance, which is carried out by the suppliers until it is established. The waterproofing system is guaranteed for 20 years.
The dwellings clad with Western Red Cedar (source: Bree Day Partnership)
Surface water run-off from the roofs is collected, treated with UV light to kill bacteria and is then stored underground for communal garden watering. Along with low flush toilets and water saving appliances, grey water recycling is installed and water from baths, showers and wash basins is recycled to flush toilets. Monitoring is taking place to establish savings in water and energy use.', '', 2001, 0, '', '', '', '', '', '', 'www.integerproject.co.uk; www.housingsolutions.co.uk; www.sustainablehomes.', '', 'urban development, adaptation action', NULL, NULL, NULL, '', 'I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (128, 1, 18, 'Gomeznarro Park, Madrid park refurbishment with storm water retention', 'In the park and its vicinity there is a considerable danger of erosion. In case of intensive rain flooding of the lower parts caused flooding at the built area. Therefore in 2003 surface drainage was made. On an area of 10000 m3 water tight pavement were demolished, compacted soil was restored or replaced, collection and infiltration tanks were located under surface and under the footpaths sewer network was installed, the footpaths were covered with permeable pavement.', '', 0, 0, 'City', '', '', '', '', '', '', '', 'adaptation action', NULL, NULL, NULL, '', 'W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (117, 1, 18, 'Millennium Green, Collingham, Newark, Nottinghamshire', 'Responding to pressures on water resources
All the buildings on the site use an automated rainwater harvesting system that has reduced water use by 50% per annum. The rainwater system uses underground storage tanks big enough to provide non-potable water to the home for 18 days. If the supply of rainwater becomes low, the tank is automatically topped up by mains supply. Homeowners are able to observe whether their tank is being supplied through the mains by a light in the control box. The harvested water is used in the homes for toilet flushing, washing machines and for gardening purposes.', '', 2002, 0, '', '', '', '', '', '', 'www.gustohomes.com; www.freerain.co.uk', '', 'urban development, adaptation action', NULL, NULL, NULL, 'E', 'I', 'M', 'W', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (118, 1, 18, 'Willingdon Levels, Eastbourne, East Sussex', 'Management of development run-off:
Developers would only receive planning permission if they voluntarily signed a Section 106 agreement setting out the volume of flood storage water required to be provided as a direct result of the development, and making a financial contribution (relative to the flood water storage displaced as a result of the particular development) to the development of compensatory lakes at Eastbourne Park, or provided the compensatory storage themselves as part of the development (e.g. Sainsbury’s provided the Broadwater Lake). Ideally the soil for the land raising would come directly from the excavated material of the compensatory flood lake being provided as part of the development. Since the scheme has been in place, 70 hectares of development in the catchment has taken place, and no flooding of properties has occurred in the catchment area.', '', 0, 0, '', '', '', '', '', '', '', '', 'urban developmant, adaptation action', NULL, NULL, NULL, 'E', 'I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (119, 1, 18, 'Wessex Water Operation Centre, Claverton Down, Bath', 'Management of development run-off and responding to pressures on water resources:
The client was very keen to promote sustainable construction within the scheme and incorporate a number of environmental-friendly designs. Water conservation measures and on-site surface drainage are also included within the scheme and an integrated water management network has been developed to avoid discharging surface water via a new sewer into the local rivers. Other measures included permeable paving in the car parking areas that allows rainwater to percolate into soakaways or large storage tanks, which feed the total irrigation requirements for the grounds. A swale runs down the western edge of the site and this also drains to the main storage tank. Water from the tank is pumped back to soakaways at the top of the site and also feeds an ornamental water feature. Furthermore, roof run-off and treated grey water are stored in three intermediate tanks and this provides 95% of the water to flush toilets.', '', 2000, 0, '', '', '', '', '', '', 'www.ciria.org', '', 'adaptation action', NULL, NULL, NULL, 'E', 'I; W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (120, 1, 18, 'Bromsgrove District Council', 'Management of development run-off:
The site at Hopwood uses a series of SUDS techniques in sequence to manage flow and control pollution which is called a ‘management train’ or treatment train. This ‘management train’ has been demonstrated to improve the flow and quality of run-off in stages prior to release into the local watercourse.
Each part of the site collects run-off in a different way but treats the 10mm ‘first flush’ in stone ‘treatment trenches’ where possible, a conventional grit / oil separator to the coach park and fuel filling area with roof water directly to a ‘feature pond’ from the amenity building. As well as helping to treat run-off and improve the overall quality of the water, SUDS also have an amenity value and provide attractive wetlands, in addition to helping to reduce flooding.', '', 1999, 0, '', '', '', '', '', '', 'www.ciria.org; www.sustainabledrainage.co.uk', '', 'adaptation action', NULL, NULL, NULL, 'E', 'W; I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (121, 1, 18, 'Water Assessment, The Netherlands', 'Management of development run-off and responding to pressures on water resources
The Netherlands is a highly urbanised delta of which a great part is situated below sea level. In the past decade the country has been faced with extremely high river discharges which forced thousands of people to evacuate, with flooded areas caused by extreme rainfall, with groundwater problems in urban areas and desiccation of nature. It is widely acknowledged that, to prevent a further increase of these problems, changes are necessary in water management as well as in spatial planning. To ensure the integration of water aspects into the spatial planning process, ‘Water Assessment’ (WA) has been introduced in 2001. Water Assessment is a process in which water managers are involved actively in the development of any spatial plan from the earliest stages on', '', 2003, 0, '', '', '', '', '', '', 'www.watertoets.net', '', '', NULL, NULL, NULL, 'E', 'I; W', 'E; M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (122, 1, 18, 'Optimise water treatment', 'The operation of sewers and waste water treatment plants will most likely face increased storm flows and more dry spells in the future. A model will be set up that describes the sediment management and treatment processes and and looks for ways to adapt.', '', 525, 0, '', '', '', '', '', '', 'http://www.regklam.de/', '', '', NULL, NULL, NULL, 'German', 'W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (123, 1, 18, 'Awareness campaings', 'Actions that promote new awareness of water conservation through more efficient water management. It emphasised, above all, the importance of simple technological changes for achieving a sustainable reduction in water consumption.', '', 525, 0, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, '', 'W', 'M', 'D', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (124, 1, 18, 'Water Recycling', 'Recycling of water for non-drinking purposes such as industry, irrigation and households. Domestic water from baths, showers and sinks can be re-used for toilets but requires filtration and disinfection. Waste water can be used for irrigation, and improvements in industrial processes now allow for the of use water  in closed cycles,  benefits of which include reducing household water demand, thereby easing pressure on the main water supply and reducing upstream energy and environmental costs.
In recent times, there has been increasing emphasis on water recycling for both non-drinking and drinking purposes. This is now being promoted as a critical sustainability issue for Australian cities.', '', 525, 0, '', '', '', '', '', '', 'http://www.nwc.gov.au/resources/documents/RecycledWaterFS-PUB-1007.pdf', '', 'adaptation action', NULL, NULL, NULL, 'E', 'W; A; I', 'M', 'D', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (204, 1, 18, 'New forests adapted to future climate', 'Climate change has been taken into consideration in two afforestation projects west of Hillerød, in North Zealand, aimed at protecting and optimising groundwater resources.

Denmark has the objective of doubling its total area of forest to approx. 20%, or 950,000 ha, before the end of this century. This means that more CO2 will be prevented from release into the atmosphere, groundwater will be protected from fertiliser resides from agriculture, and a more varied natural landscape will be created, with a high degree of biodiversity. There are therefore many projects underway around the country where forests are being planted which are suited to a climate with warmer winters, greater precipitation, and more violent storms. For example, 1000 ha of new forest in North Zealand will be adapted to the future climate.

“The primary aim of the project is to protect existing groundwater resources and provide potential for new ones. By purchasing agricultural land and planting forests instead, we will ensure that pesticides and chemicals from fertilisers do not seep into the groundwater in the future. There is therefore a ban on the use of fertiliser and pesticides on all the land we are purchasing”, explains a ranger from the North Zealand office of the Danish Forest and Nature Agency, who is project leader for the two afforestation projects.', '', 0, 0, '', '', '', '', 'Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/newforestsadaptedtofutureclimate.aspx', '', '', NULL, NULL, NULL, '', 'A', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (205, 1, 18, 'New storm surge scheme to promote climate change adaptation actions', 'Prevent damage to your property - or pay more excess insurance. This is the principle in a proposed new Danish storm surge scheme. The scheme will promote climate change adaptation actions.

In autumn 2009, a committee set up by the Danish Storm Council published a report on the revision of the existing Danish storm surge scheme (‘Rapport om Revision af Stormflodsordning’), suggested a series of changes to the scheme. This has led to a bill, which is currently before the Danish Parliament. 

The changes in the bill provide incentives for climate change adaptation actions. Some of the changes include a new compensation model, a so-called stepwise model, where the excess payable on insurance claims is increased if repeated damage occurs at the same address. This is to promote prevention of damage caused by climate change events such as flooding and storm surges.', '', 0, 0, '', '', '', '', 'Lisbeth Strandmark
Danish Energy Agency
Phone: +45 33 92 19

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/newstormsurgeschemetopromoteclimatechangeadaptationactions.aspx', '', '', NULL, NULL, NULL, '', 'F', 'M', 'F; S', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (125, 1, 18, 'Rainwater and stormwater managment in urban areas', 'Rainwater can be used for irrigation purposes, car washing or toilet flushing and is beneficial for two reasons:
(i) it reduces water demand and eases pressure on the main water supply, reducing upstream energy and environmental costs
(ii) it helps to reduce the risk of flooding during storms by storing rainwater and buffering run-off before it reaches drains. Rainwater overflow is particularly problematic in those cities where rainwater and sewage water are not separated. Options in this measure include those for water storage and retention in or near city areas
It is implemented through artificial infiltration and retardation, reduced impermeable area, pervious pavements and parking lots, local storages (ponds, building storages, groundwater cisterns); roof planting. It also includes increase of storage in the river system which can be achieved by development of flood plains, polders, and wetlands. Permeability taxation can enhance reconstruction of green areas in cities. By promoting infiltration, storage and trapping water in the catchments, flood peaks can be lowered. Improvement of drainage system can also enhance water storing.', '', 525, 0, '', '', '', '', '', '', 'http://cweb.salisbury.sa.gov.au/manifest/servlet/page?pg=16081', '', '', NULL, NULL, NULL, '', 'W; A; I', 'M', 'W; F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (206, 1, 18, 'No more overloaded sewer systems', 'Over the coming 90 years combined sewer systems will be phased out in the Municipality of Aalborg. Instead, the Municipality will introduce separate systems for stormwater and sewage.', '', 0, 0, '', '', '', '', 'Bo Laden
The Public Utility Department, Municipality of Aalborg
phone: +45 9931 9390

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/nomoreoverloadedsewer.aspx', '', '', NULL, NULL, NULL, '', 'W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (207, 1, 18, 'Can the roads cope with more water?', 'Some stretches of the Danish roads are not ready for the increased quantities of water expected in the future, while others have been designed to cope.

Roads with built-in drainage
All in all it makes good sense for municipalities to include climate change considerations in their future traffic and infrastructure planning. Both in order to avoid flooding, but also to be better at controlling water flows. As an example, the Municipality of Roskilde has done this when planning the new housing development at ‘Trekroner Øst’, which is situated just next to Roskilde University.', '', 0, 0, '', '', '', '', 'Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/cantheroadscopewithmorewater.aspx', '', '', NULL, NULL, NULL, '', 'I; W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (210, 1, 18, 'Re-rigging vessels and new forms of fisheries management', 'Climate change will require development of new fishing technology and fishing gear. Managing authorities must put climate change into the equation when allocating fishing quotas.', '', 0, 0, '', '', '', '', 'Anette Engelund Friis
Ministry of Food, Agriculture and Fisheries
Phone: +45 3392 2142

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/re-riggingvesselsandnewformsoffisheriesmanagement.aspx', '', '', NULL, NULL, NULL, '', 'M', 'M', '', 'M');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (211, 1, 18, 'Dykes alone are not enough', 'The municipality of Dragør has moved away from an ‘insensitive’ coastal defences policy Instead, the municipality has chosen nature’s own technology for adaptation to the climate of the future.

The great idea behind the municipality’s green blue plan and local climate strategy is to avoid an ‘insensitive’ coastal defence policy and instead to employ nature’s own technology and to some extent allow nature to adapt to altered climate conditions on its own.

“The concept of allowing the biodiversity that exists in our beach meadows to spread inland is very exciting. This is of course a controversial concept, because it means that in the long run farmers will have to abandon some of their farmland, but it will provide Dragør with entirely new recreational opportunities. There is also the possibility of coastal defences that accommodate beach meadow biotopes dependant on occasional flooding,”
In its green blue plan the municipality is planning an ‘urban fringe zone’ between Dragør and the neighbouring village of Store Magleby. This urban fringe zone is to be a buffer zone with recreational areas and areas where the water is delayed, can evaporate, or can percolate into the groundwater.', '', 0, 0, '', '', '', '', 'Jørgen Jensen
Department Head, Planing and Building
Municipality of Dragør
Phone: +45 3289 0331
joergenj@dragoer.dk

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/dykesalonearenotenough.aspx', '', '', NULL, NULL, NULL, '', 'C; W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (212, 1, 18, 'Seawater keeps Copenhagen buildings cool', 'District cooling of buildings using seawater or surplus heat, can prevent us from emitting large amounts of greenhouse gases into the atmosphere. The very first district cooling plant in Denmark is now ready to pump cold water into distribution pipes.', '', 0, 0, '', '', '', '', 'Jan Don Høgh
Copenhagen Energy
Phone: +45 3395 3395
ke@ke.dk

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/seawaterkeepscopenhagenbuildingscool.aspx', '', '', NULL, NULL, NULL, '', 'I', 'M', 'E', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (213, 1, 18, 'Give us our sandy beaches back', 'The north coast of Sealand needs to be replenished with sand in order to restore its beaches and protect the coastline.

This situation has led a group of homeowners to propose a common project: The coast is to be nourished with 250,000m3 of sand each year for three years and subsequently with 50,000m3 annually. This should restore the wide sandy beaches and stop the coastal cliffs from degrading.', '', 0, 0, '', '', '', '', 'Bodil Harder
Danish Energy Agency
Phone: +45 3392 6871

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/giveusoursandybeachesback.aspx', '', '', NULL, NULL, NULL, '', 'C', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (217, 1, 18, 'The forest must renew itself', 'Conifers are on the way out at the Gjorslev estate on the peninsular of Stevns on Sealand. A changing climate will make deciduous forestry a far better business.

The conversion at Gjorslev to even more deciduous forest, managed according to close-to-nature principles has taken place gradually over a longer period of time and not only as a response to climate change. The conversion is also good business.
“It is extremely expensive to plant and protect new trees, so it is a real advantage to let the trees regenerate through natural seeding and spend the resources on nurturing the forest instead,” explains Peter Henrik Tesdorpf.

“By mixing different tree species and trees of different ages, you get a forest where you can change the composition of trees over time by choosing the trees to be removed during thinning and the trees to be allowed to regenerate.  In this way foresters can spread their risk and adapt forests to climate change impacts as they become reality,” Bo Larsen argues.', '', 0, 0, '', '', '', '', 'Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/theforestmustrenewitself.aspx', '', '', NULL, NULL, NULL, '', 'A', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (218, 1, 18, 'Adapting railways to climate change', 'Increased precipitation and increased water flow in watercourses can affect the new railway line between Copenhagen and Ringsted.

At places where watercourse cross the track, under a bridge or tunnel, climate changes mean there is a risk that water can not flow quickly enough and thereby build up and risk eroding the railway construction.  Therefore a new track between Copenhagen and Ringsted will have a 30 per cent greater capacity for water flow than the norm that is used at present. The Public Transport Authority assesses that the recommendations for adaptation to climate change are robust in relation to the variations in the expected climate changes.', '', 0, 0, '', '', '', '', 'Ministry of Transport
Natascha Krogager Carlsson
Phone: +45 3392 3309
nkc@trm.dk

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/adaptingrailwaystoclimatechange.aspx', '', '', NULL, NULL, NULL, '', 'I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (129, 1, 18, 'Danube-Carpathian Region', 'The project focuses on the development of an action plan for adaptation to climate change in the Danube-Carpathian Region. Climate change is projected to cause an increase in extreme weather events, with an inevitable knock-on effect on natural habitats, species and local populations. 
It will attempt to communicate the required urgency for action on climate change to both governments and the public within the region.', '', 0, 0, '', '', '', '', '', '', 'http://wwf.panda.org/what_we_do/where_we_work/black_sea_basin/danube_carpathian/', '', 'Raise awareness, extreme weather events', NULL, NULL, NULL, 'E', 'A;B;C;D;F;H;I;M;W;', 'M; P', '', 'M');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (202, 1, 18, 'Climate change paves the way for new tourism concept', 'The invasive species Pacific oyster has spread rapidly in the Wadden Sea in recent years. The oysters create problems for the Wadden Sea ecosystem, but are also an opportunity for attracting tourists to the area.

Usually, between 20 and 50 paying guests participate in Sort Safari’s oyster safari, which is held once a week during summer and twice an month during winter. There are guests from the local area, from throughout Denmark and also from Sweden. The Swedes find going on an oyster hunt to Denmark exotic. Besides Sort Safari, others also arrange oyster hunts, including the Wadden Sea Centre, the Fanoe Tourist Office and Nature Centre Tønnisgård. The many visitors to the Wadden Sea are economically important to this area, one of Denmark’s most sparsely populated.', '', 0, 0, '', '', '', '', '', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/climatechangepavesthewayfornewtourismconcept.aspx', '', '', NULL, NULL, NULL, '', 'B', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (203, 1, 18, 'New educations in climate change adaptation', 'Green Urban Transformers, Master of Disaster Management, Garden and Park Engineering, and Roof Gardener. These are just a few of the new training programmes offered in Denmark focussing on climate change

Predictions of the future climate in Denmark indicate that we will be seeing more and more extreme weather events. If we are not well prepared, this could have considerable implications for both nature and society. Specialists with knowledge on how to prevent, manage and adapt to the new conditions will be in great demand. Therefore, an increasing number of practical and academic training programmes are emerging, all offering teaching in various facets of climate change adaptation.', '', 0, 0, '', '', '', '', 'Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk
Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/newtrainingprogrammesinclimatechangeadaptation.aspx', '', '', NULL, NULL, NULL, '', 'I; D', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (208, 1, 18, 'Storm surge tool for the public and for the emergency services in Nyborg on', 'Residents in Nyborg on the coast of the Danish island of Funen can visit the municipality’s website to check out whether their house is at risk of flooding in the event of rising sea levels.

The municipality of Nyborg has a tool for analysing storm-surge scenarios on their website. This tool can calculate which areas are at risk of being flooded at given increases in water levels.', '', 0, 0, '', '', '', '', '', 'Municipality of Nyborg

Poul Laursen
Phone: +45 6333 7784
pla@nyborg.dk

Preben Petersen 
Phone: +45 6333 6823
psp@nyborg.dk
 
Birgit Sønderskov Weber
Phone: +45 6333 6820
bsw@nyborg.dk', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/stormsurgetoolforthepublicandfortheemergencyservicesinnyborgonfunen.aspx', '', '', NULL, NULL, NULL, '', 'I', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (220, 1, 18, 'NCoE NORD-STAR (Nordic Strategic Adaptation Research)', 'NORD-STAR research shall lead to better support for decision-making and strategy development by linking adaptation and mitigation, and using climate visualization techniques and decision-making tools to bridge the gap between science and policy at the Nordic level. The research is designed to help Nordic countries maintain competitive advantages and identify cost-effective adaptation measures.
A core objective of NORD-STAR is to develop practical, easily accessible and user-friendly tools, which shall enhance the adaptive capacity of among others: planners, civil servants, organisations, industries and decision-makers in the Nordic countries. Consequently, dissemination is an integral and important part of the project.', '', 0, 0, '', '', '', '', 'Michael Goodsite, National Environmental Research Institute, Aarhus University (mgo@dmu.dk)', '', 'http://www.toppforskningsinitiativet.org/en/programmer-1/program-1/prosjekter/ncoe-nord-star-nordic-strategic-adaptation-research', '', '', NULL, NULL, NULL, 'En', 'A;B;C;D;F;H;I;M;W;', 'M', '', 'M');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (209, 1, 18, 'Climate-adapted hospitals require collaboration', 'Danish hospitals must be equipped for climate change. This requires better collaboration between architects and engineers, as well as forward-looking developers.

“Climate-adapted buildings in Denmark should primarily take two things into account: higher temperatures and rises in water-level. While water levels are an important factor in low-lying areas near the coast, adapting to a warmer climate is something that should be incorporated into all building projects in future,” says Olaf Bruun Jørgensen, head of department at Esbensen Consulting Engineers.

This applies not least to hospital buildings, where the indoor climate is particularly important. A fine example is the refurbishing of the southern Jutland regional hospital in Aabenraa. In 2003-2004 the hospital had its three courtyards roofed over to provide more space for both employees and patients. The courtyards were glazed over, solar panels and solar shading were installed, along with natural ventilation (hybrid ventilation) and double facades (double-skin facades). In addition to substantial cuts in energy consumption, these changes have provided natural light conditions and a good and healthy indoor climate.', '', 0, 0, '', '', '', '', 'Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/climate-adaptedhospitalsrequirecollaboration.aspx', '', '', NULL, NULL, NULL, '', 'H', 'M', 'E', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (214, 1, 18, 'Demolished houses transformed into scenic lakes', 'A new recreational area is the result of innovative cooperation between home owners and Odense Water Ltd. who together solved the problems of flooded basements after extreme downpours.

Following unusual developments in events since the summer of 2006, a solution was found. Odense Water Ltd. bought seven of the particularly flood-prone houses in an area where two new lakes (basins) with greenery could be established. In March 2009 work started on demolishing the houses and excavating the basins.

The three new basins can hold about 10,000m3, which means that they can cope with powerful downpours, statistically likely to occur only once every 50 years. So, the suburb of Sanderum has acquired a new recreational area to enjoy and the residents that remain no longer need to worry about flooded basements. The project has cost about DKK 30 mill. including the purchase of the seven houses.', '', 0, 0, '', '', '', '', 'Nena Kroghsbo
VCS Denmark
Phone: +45 6313 2317 

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/demolishedhousestransformedintosceniclakes.aspx', '', '', NULL, NULL, NULL, '', 'W', 'M', 'F', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (215, 1, 18, 'Farmer harvests twice a year', 'On Mors, a small island in the Limfjord in northern Jutland, Herluf Hensberg has taken a peep at farming practices of the future adapted to a new climate, and in doing so he has greatly inspired his fellow farmers.

In reality, no one actually believed that Herluf Hensberg would be able to do it.  No one has ever managed two harvests a year in Denmark. Harvesting twice a year has traditionally been reserved for farmers in far warmer regions. However, last year when Mr Hensberg decided nonetheless to attempt bringing in the harvest from his fields twice during the same year, this was no far-fetched idea.  The climate is changing, so why not give it a try, as Mr Hensberg explains.

“We are seeing the effects already. Today we harvest some 14 days earlier than just 10 years ago. And last year the harvest promised to fall even earlier, so we decided to give it a try and sow a special type of Swedish barley as soon as our winter barley had been harvested.   The type of barley that we sowed has been developed for cultivation in the far north, where the growing season is very short, so we thought, let’s try with 15 hectares of this barley and see how it goes,” says Herluf Hensberg.', '', 0, 0, '', '', '', '', 'Herluf Hensberg

Phone: +45 9776 6366

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/farmerharveststwiceayear.aspx', '', '', NULL, NULL, NULL, '', 'A', 'M', '', 'A');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (216, 1, 18, 'Hedensted plans ahead for a new climate', 'The Danish municipality of Hedensted is in the process of tackling the problems already caused by a changing climate while at the same time safeguarding against future climate change.

Climate change adaptation is incorporated into plans
So Hedensted is really not that different from other Danish municipalities. However, when it comes to further work on safeguarding the municipality’s buildings, homes, green areas, etc. against a changing climate, the municipality is at the forefront. This year, the municipality will adopt its first ‘climate-adapted’ municipal plan.

The municipal plan is the general plan for development in the municipality during the next twelve years. The plan is adjusted every four years, and for the first time climate developments have been incorporated in the version of the plan to be adopted by the end of 2009, so that all future construction works and land-use designations take account of more precipitation, rising sea levels and other predictable climate change impacts.', '', 0, 0, '', '', '', '', 'Municipality of Hedensted
Planner: Niels Rauff
Phone: +45 7975 5690

Plan09
Planner: Christina Hoffer
Phone: +45 7254 4737

Information Center for Climate Change Adaptation    Danish Ministry of Climate and Energy Danish Meteorological Institute   ; Lyngbyvej 100    2100 Copenhagen K   Tlf. +45 39157500
e-mail: klimatilpasning@dmi.dk', '', 'http://www.klimatilpasning.dk/en-us/service/cases/sider/hedenstedplansaheadforanewclimate.aspx', '', '', NULL, NULL, NULL, '', 'A;B;C;D;F;H;I;M;W;', 'M', '', 'M');
INSERT INTO ace_measure (measureid, companyid, groupid, name, description, implementationtype, implementationtime, lifetime, spatiallayer, spatialvalues, legalaspects, stakeholderparticipation, contact, succeslimitations, website, costbenefit, keywords, startdate, enddate, publicationdate, language, sectors_, elements_, climateimpacts_, mao_type) VALUES (219, 1, 18, 'NCoE Tundra (How to preserve the tundra in a warming climate?)', 'A warmer climate threatens to change most of the current tundra to forest or dense scrubland, unsuitable for arctic-alpine plants. Vegetation changes may also speed up global warming.
The aim of this NCoE is to find methods to preserve arctic-alpine biota in a warmer climate. The idea is to use herbivorous mammals to control the expansion of woody vegetation. Recent studies show that forest expansion can be prevented by the combination of relatively sparse reindeer stocks and natural populations of arvicoline rodents.
The Centre will study the dynamics of the natural food chains involving small herbivorous mammals to identify habitats where the impact of small mammals suffices to control the forest expansion.
They will also study the impacts of reindeer on the vegetation and population dynamics of those arctic-alpine plants that are most likely to become threatened in a warmer climate.

What are the conditions for maintaining the economic and cultural viability of reindeer herding and direct land use in order to contribute to the preservation of open landscapes suitable for arctic-alpine biota?', '', 0, 0, '', '', '', '', 'Lauri Oksanen, Finnmark University College and University of Turku (lauoks@utu.fi)', '', 'http://www.toppforskningsinitiativet.org/en/programmer-1/program-1/prosjekter/ncoe-how-to-preserve-the-tundra-in-a-warming-climate', '', '', NULL, NULL, NULL, '', 'B', 'M', '', 'M');


-- Completed on 2011-04-06 12:56:37

--
-- PostgreSQL database dump complete
--

