create table Ace_Measure (
	measureId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	implementationtype VARCHAR(75) null,
	implementationtime VARCHAR(75) null,
	lifetime VARCHAR(75) null,
	spatiallayer VARCHAR(75) null,
	spatialvalues VARCHAR(75) null,
	legalaspects VARCHAR(75) null,
	stakeholderparticipation VARCHAR(75) null,
	contact VARCHAR(75) null,
	succeslimitations VARCHAR(75) null,
	website VARCHAR(75) null,
	costbenefit VARCHAR(75) null,
	keywords VARCHAR(75) null,
	startdate DATE null,
	enddate DATE null,
	publicationdate DATE null,
	language VARCHAR(75) null,
	sectors_ VARCHAR(75) null,
	elements_ VARCHAR(75) null,
	climateimpacts_ VARCHAR(75) null,
	mao_type VARCHAR(75) null
);