create table Ace_Measure (
	measureId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	admincomment VARCHAR(2500) null,
	casestudyfeature VARCHAR(75) null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	implementationtype VARCHAR(75) null,
	implementationtime VARCHAR(75) null,
	lifetime VARCHAR(75) null,
	spatiallayer VARCHAR(75) null,
	spatialvalues VARCHAR(75) null,
	legalaspects VARCHAR(75) null,
	stakeholderparticipation VARCHAR(75) null,
	contact VARCHAR(75) null,
	objectives VARCHAR(3900) null,
	challenges VARCHAR(3900) null,
	adaptationoptions VARCHAR(500) null,
	solutions VARCHAR(3900) null,
	relevance VARCHAR(75) null,
	succeslimitations VARCHAR(75) null,
	website VARCHAR(75) null,
	costbenefit VARCHAR(75) null,
	keywords VARCHAR(75) null,
	geos_ VARCHAR(75) null,
	startdate DATE null,
	enddate DATE null,
	publicationdate DATE null,
	specialtagging VARCHAR(75) null,
	sectors_ VARCHAR(75) null,
	elements_ VARCHAR(75) null,
	climateimpacts_ VARCHAR(75) null,
	mao_type VARCHAR(75) null,
	source VARCHAR(75) null,
	rating LONG,
	importance LONG,
	lon DOUBLE,
	lat DOUBLE,
	satarea VARCHAR(75) null,
	controlstatus INTEGER,
	creator VARCHAR(75) null,
	creationdate DATE null,
	moderator VARCHAR(75) null,
	approvaldate DATE null,
	replacesId LONG,
	comments VARCHAR(75) null,
	textwebpage VARCHAR(75) null,
	primephoto VARCHAR(75) null,
	supphotos VARCHAR(75) null,
	supdocs VARCHAR(75) null,
	year VARCHAR(75) null,
	geochars VARCHAR(2500) null
);