/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.wur.alterra.cgi.ace.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import nl.wur.alterra.cgi.ace.model.AceItem;
import nl.wur.alterra.cgi.ace.model.AceItemModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the AceItem service. Represents a row in the &quot;Ace_AceItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link nl.wur.alterra.cgi.ace.model.AceItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AceItemImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a ace item model instance should use the {@link nl.wur.alterra.cgi.ace.model.AceItem} interface instead.
 * </p>
 *
 * @author groot052
 * @see AceItemImpl
 * @see nl.wur.alterra.cgi.ace.model.AceItem
 * @see nl.wur.alterra.cgi.ace.model.AceItemModel
 * @generated
 */
public class AceItemModelImpl extends BaseModelImpl<AceItem>
	implements AceItemModel {
	public static final String TABLE_NAME = "Ace_AceItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "aceItemId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "description", new Integer(Types.VARCHAR) },
			{ "type_", new Integer(Types.VARCHAR) },
			{ "storedAt", new Integer(Types.VARCHAR) },
			{ "sector", new Integer(Types.VARCHAR) },
			{ "pilar", new Integer(Types.VARCHAR) },
			{ "textSearch", new Integer(Types.VARCHAR) },
			{ "keyword", new Integer(Types.VARCHAR) },
			{ "nutsId", new Integer(Types.VARCHAR) },
			{ "nutsLevel", new Integer(Types.VARCHAR) },
			{ "startDate", new Integer(Types.TIMESTAMP) },
			{ "endDate", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table Ace_AceItem (aceItemId LONG not null primary key,companyId LONG,groupId LONG,name VARCHAR(75) null,description VARCHAR(75) null,type_ VARCHAR(75) null,storedAt VARCHAR(75) null,sector VARCHAR(75) null,pilar VARCHAR(75) null,textSearch VARCHAR(75) null,keyword VARCHAR(75) null,nutsId VARCHAR(75) null,nutsLevel VARCHAR(75) null,startDate DATE null,endDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Ace_AceItem";
	public static final String ORDER_BY_JPQL = " ORDER BY aceItem.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Ace_AceItem.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.nl.wur.alterra.cgi.ace.model.AceItem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.nl.wur.alterra.cgi.ace.model.AceItem"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.nl.wur.alterra.cgi.ace.model.AceItem"));

	public AceItemModelImpl() {
	}

	public long getPrimaryKey() {
		return _aceItemId;
	}

	public void setPrimaryKey(long pk) {
		setAceItemId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_aceItemId);
	}

	public long getAceItemId() {
		return _aceItemId;
	}

	public void setAceItemId(long aceItemId) {
		_aceItemId = aceItemId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	public void setType(String type) {
		_type = type;
	}

	public String getStoredAt() {
		if (_storedAt == null) {
			return StringPool.BLANK;
		}
		else {
			return _storedAt;
		}
	}

	public void setStoredAt(String storedAt) {
		_storedAt = storedAt;
	}

	public String getSector() {
		if (_sector == null) {
			return StringPool.BLANK;
		}
		else {
			return _sector;
		}
	}

	public void setSector(String sector) {
		_sector = sector;
	}

	public String getPilar() {
		if (_pilar == null) {
			return StringPool.BLANK;
		}
		else {
			return _pilar;
		}
	}

	public void setPilar(String pilar) {
		_pilar = pilar;
	}

	public String getTextSearch() {
		if (_textSearch == null) {
			return StringPool.BLANK;
		}
		else {
			return _textSearch;
		}
	}

	public void setTextSearch(String textSearch) {
		_textSearch = textSearch;
	}

	public String getKeyword() {
		if (_keyword == null) {
			return StringPool.BLANK;
		}
		else {
			return _keyword;
		}
	}

	public void setKeyword(String keyword) {
		_keyword = keyword;
	}

	public String getNutsId() {
		if (_nutsId == null) {
			return StringPool.BLANK;
		}
		else {
			return _nutsId;
		}
	}

	public void setNutsId(String nutsId) {
		_nutsId = nutsId;
	}

	public String getNutsLevel() {
		if (_nutsLevel == null) {
			return StringPool.BLANK;
		}
		else {
			return _nutsLevel;
		}
	}

	public void setNutsLevel(String nutsLevel) {
		_nutsLevel = nutsLevel;
	}

	public Date getStartDate() {
		return _startDate;
	}

	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	public Date getEndDate() {
		return _endDate;
	}

	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	public AceItem toEscapedModel() {
		if (isEscapedModel()) {
			return (AceItem)this;
		}
		else {
			return (AceItem)Proxy.newProxyInstance(AceItem.class.getClassLoader(),
				new Class[] { AceItem.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					AceItem.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		AceItemImpl clone = new AceItemImpl();

		clone.setAceItemId(getAceItemId());
		clone.setCompanyId(getCompanyId());
		clone.setGroupId(getGroupId());
		clone.setName(getName());
		clone.setDescription(getDescription());
		clone.setType(getType());
		clone.setStoredAt(getStoredAt());
		clone.setSector(getSector());
		clone.setPilar(getPilar());
		clone.setTextSearch(getTextSearch());
		clone.setKeyword(getKeyword());
		clone.setNutsId(getNutsId());
		clone.setNutsLevel(getNutsLevel());
		clone.setStartDate(getStartDate());
		clone.setEndDate(getEndDate());

		return clone;
	}

	public int compareTo(AceItem aceItem) {
		int value = 0;

		value = getName().compareTo(aceItem.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		AceItem aceItem = null;

		try {
			aceItem = (AceItem)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = aceItem.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{aceItemId=");
		sb.append(getAceItemId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", storedAt=");
		sb.append(getStoredAt());
		sb.append(", sector=");
		sb.append(getSector());
		sb.append(", pilar=");
		sb.append(getPilar());
		sb.append(", textSearch=");
		sb.append(getTextSearch());
		sb.append(", keyword=");
		sb.append(getKeyword());
		sb.append(", nutsId=");
		sb.append(getNutsId());
		sb.append(", nutsLevel=");
		sb.append(getNutsLevel());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("nl.wur.alterra.cgi.ace.model.AceItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>aceItemId</column-name><column-value><![CDATA[");
		sb.append(getAceItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>storedAt</column-name><column-value><![CDATA[");
		sb.append(getStoredAt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sector</column-name><column-value><![CDATA[");
		sb.append(getSector());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pilar</column-name><column-value><![CDATA[");
		sb.append(getPilar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>textSearch</column-name><column-value><![CDATA[");
		sb.append(getTextSearch());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keyword</column-name><column-value><![CDATA[");
		sb.append(getKeyword());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nutsId</column-name><column-value><![CDATA[");
		sb.append(getNutsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nutsLevel</column-name><column-value><![CDATA[");
		sb.append(getNutsLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _aceItemId;
	private long _companyId;
	private long _groupId;
	private String _name;
	private String _description;
	private String _type;
	private String _storedAt;
	private String _sector;
	private String _pilar;
	private String _textSearch;
	private String _keyword;
	private String _nutsId;
	private String _nutsLevel;
	private Date _startDate;
	private Date _endDate;
	private transient ExpandoBridge _expandoBridge;
}