package nl.wur.alterra.cgi.ace.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import nl.wur.alterra.cgi.ace.model.AceItem;
import nl.wur.alterra.cgi.ace.service.AceItemLocalServiceUtil;

/**
 * The extended model base implementation for the AceItem service. Represents a row in the &quot;Ace_AceItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AceItemImpl}.
 * </p>
 *
 * @author groot052
 * @see AceItemImpl
 * @see nl.wur.alterra.cgi.ace.model.AceItem
 * @generated
 */
public abstract class AceItemBaseImpl extends AceItemModelImpl
    implements AceItem {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ace item model instance should use the {@link AceItem} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AceItemLocalServiceUtil.addAceItem(this);
        } else {
            AceItemLocalServiceUtil.updateAceItem(this);
        }
    }
}
