package nl.wur.alterra.cgi.ace.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import nl.wur.alterra.cgi.ace.model.CSWHarvester;
import nl.wur.alterra.cgi.ace.service.CSWHarvesterLocalServiceUtil;

/**
 * The extended model base implementation for the CSWHarvester service. Represents a row in the &quot;Ace_CSWHarvester&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CSWHarvesterImpl}.
 * </p>
 *
 * @author groot052
 * @see CSWHarvesterImpl
 * @see nl.wur.alterra.cgi.ace.model.CSWHarvester
 * @generated
 */
public abstract class CSWHarvesterBaseImpl extends CSWHarvesterModelImpl
    implements CSWHarvester {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a c s w harvester model instance should use the {@link CSWHarvester} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CSWHarvesterLocalServiceUtil.addCSWHarvester(this);
        } else {
            CSWHarvesterLocalServiceUtil.updateCSWHarvester(this);
        }
    }
}
