/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.wur.alterra.cgi.ace.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import nl.wur.alterra.cgi.ace.model.NASSource;
import nl.wur.alterra.cgi.ace.model.NASSourceModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the NASSource service. Represents a row in the &quot;Ace_NASSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link nl.wur.alterra.cgi.ace.model.NASSourceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NASSourceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a n a s source model instance should use the {@link nl.wur.alterra.cgi.ace.model.NASSource} interface instead.
 * </p>
 *
 * @author groot052
 * @see NASSourceImpl
 * @see nl.wur.alterra.cgi.ace.model.NASSource
 * @see nl.wur.alterra.cgi.ace.model.NASSourceModel
 * @generated
 */
public class NASSourceModelImpl extends BaseModelImpl<NASSource>
	implements NASSourceModel {
	public static final String TABLE_NAME = "Ace_NASSource";
	public static final Object[][] TABLE_COLUMNS = {
			{ "nassourceid", new Integer(Types.BIGINT) },
			{ "nasId", new Integer(Types.BIGINT) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table Ace_NASSource (nassourceid LONG not null primary key,nasId LONG,name VARCHAR(75) null,companyId LONG,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Ace_NASSource";
	public static final String ORDER_BY_JPQL = " ORDER BY nasSource.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Ace_NASSource.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.nl.wur.alterra.cgi.ace.model.NASSource"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.nl.wur.alterra.cgi.ace.model.NASSource"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.nl.wur.alterra.cgi.ace.model.NASSource"));

	public NASSourceModelImpl() {
	}

	public long getPrimaryKey() {
		return _nassourceid;
	}

	public void setPrimaryKey(long pk) {
		setNassourceid(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_nassourceid);
	}

	public long getNassourceid() {
		return _nassourceid;
	}

	public void setNassourceid(long nassourceid) {
		_nassourceid = nassourceid;
	}

	public long getNasId() {
		return _nasId;
	}

	public void setNasId(long nasId) {
		_nasId = nasId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public NASSource toEscapedModel() {
		if (isEscapedModel()) {
			return (NASSource)this;
		}
		else {
			return (NASSource)Proxy.newProxyInstance(NASSource.class.getClassLoader(),
				new Class[] { NASSource.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					NASSource.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		NASSourceImpl clone = new NASSourceImpl();

		clone.setNassourceid(getNassourceid());
		clone.setNasId(getNasId());
		clone.setName(getName());
		clone.setCompanyId(getCompanyId());
		clone.setGroupId(getGroupId());

		return clone;
	}

	public int compareTo(NASSource nasSource) {
		int value = 0;

		value = getName().toLowerCase()
					.compareTo(nasSource.getName().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		NASSource nasSource = null;

		try {
			nasSource = (NASSource)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = nasSource.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{nassourceid=");
		sb.append(getNassourceid());
		sb.append(", nasId=");
		sb.append(getNasId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("nl.wur.alterra.cgi.ace.model.NASSource");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>nassourceid</column-name><column-value><![CDATA[");
		sb.append(getNassourceid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nasId</column-name><column-value><![CDATA[");
		sb.append(getNasId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _nassourceid;
	private long _nasId;
	private String _name;
	private long _companyId;
	private long _groupId;
	private transient ExpandoBridge _expandoBridge;
}