package nl.wur.alterra.cgi.ace.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import nl.wur.alterra.cgi.ace.model.Measure;
import nl.wur.alterra.cgi.ace.service.MeasureLocalServiceUtil;

/**
 * The extended model base implementation for the Measure service. Represents a row in the &quot;Ace_Measure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeasureImpl}.
 * </p>
 *
 * @author groot052
 * @see MeasureImpl
 * @see nl.wur.alterra.cgi.ace.model.Measure
 * @generated
 */
public abstract class MeasureBaseImpl extends MeasureModelImpl
    implements Measure {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a measure model instance should use the {@link Measure} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MeasureLocalServiceUtil.addMeasure(this);
        } else {
            MeasureLocalServiceUtil.updateMeasure(this);
        }
    }
}
