#!/bin/sh
# Discover
#./rdfexport -d database.properties  -r rdfexport.properties -m lfacegis -x -p discovered.properties

# RUN project
./rdfexport -d database.properties  -f lfacegis.properties -m lfacegis -z -o climateadapt.rdf.gz

