package nl.wur.alterra.cgi.ace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;Ace_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link nl.wur.alterra.cgi.ace.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link nl.wur.alterra.cgi.ace.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Groot052
 * @see Project
 * @see nl.wur.alterra.cgi.ace.model.impl.ProjectImpl
 * @see nl.wur.alterra.cgi.ace.model.impl.ProjectModelImpl
 * @generated
 */
public interface ProjectModel extends BaseModel<Project> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
     */

    /**
     * Returns the primary key of this project.
     *
     * @return the primary key of this project
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this project.
     *
     * @param primaryKey the primary key of this project
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the project ID of this project.
     *
     * @return the project ID of this project
     */
    public long getProjectId();

    /**
     * Sets the project ID of this project.
     *
     * @param projectId the project ID of this project
     */
    public void setProjectId(long projectId);

    /**
     * Returns the company ID of this project.
     *
     * @return the company ID of this project
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this project.
     *
     * @param companyId the company ID of this project
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this project.
     *
     * @return the group ID of this project
     */
    public long getGroupId();

    /**
     * Sets the group ID of this project.
     *
     * @param groupId the group ID of this project
     */
    public void setGroupId(long groupId);

    /**
     * Returns the admincomment of this project.
     *
     * @return the admincomment of this project
     */
    @AutoEscape
    public String getAdmincomment();

    /**
     * Sets the admincomment of this project.
     *
     * @param admincomment the admincomment of this project
     */
    public void setAdmincomment(String admincomment);

    /**
     * Returns the acronym of this project.
     *
     * @return the acronym of this project
     */
    @AutoEscape
    public String getAcronym();

    /**
     * Sets the acronym of this project.
     *
     * @param acronym the acronym of this project
     */
    public void setAcronym(String acronym);

    /**
     * Returns the title of this project.
     *
     * @return the title of this project
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this project.
     *
     * @param title the title of this project
     */
    public void setTitle(String title);

    /**
     * Returns the startdate of this project.
     *
     * @return the startdate of this project
     */
    public Date getStartdate();

    /**
     * Sets the startdate of this project.
     *
     * @param startdate the startdate of this project
     */
    public void setStartdate(Date startdate);

    /**
     * Returns the enddate of this project.
     *
     * @return the enddate of this project
     */
    public Date getEnddate();

    /**
     * Sets the enddate of this project.
     *
     * @param enddate the enddate of this project
     */
    public void setEnddate(Date enddate);

    /**
     * Returns the lead of this project.
     *
     * @return the lead of this project
     */
    @AutoEscape
    public String getLead();

    /**
     * Sets the lead of this project.
     *
     * @param lead the lead of this project
     */
    public void setLead(String lead);

    /**
     * Returns the partners of this project.
     *
     * @return the partners of this project
     */
    @AutoEscape
    public String getPartners();

    /**
     * Sets the partners of this project.
     *
     * @param partners the partners of this project
     */
    public void setPartners(String partners);

    /**
     * Returns the funding of this project.
     *
     * @return the funding of this project
     */
    @AutoEscape
    public String getFunding();

    /**
     * Sets the funding of this project.
     *
     * @param funding the funding of this project
     */
    public void setFunding(String funding);

    /**
     * Returns the sectors of this project.
     *
     * @return the sectors of this project
     */
    @AutoEscape
    public String getSectors();

    /**
     * Sets the sectors of this project.
     *
     * @param sectors the sectors of this project
     */
    public void setSectors(String sectors);

    /**
     * Returns the spatiallayer of this project.
     *
     * @return the spatiallayer of this project
     */
    @AutoEscape
    public String getSpatiallayer();

    /**
     * Sets the spatiallayer of this project.
     *
     * @param spatiallayer the spatiallayer of this project
     */
    public void setSpatiallayer(String spatiallayer);

    /**
     * Returns the abstracts of this project.
     *
     * @return the abstracts of this project
     */
    @AutoEscape
    public String getAbstracts();

    /**
     * Sets the abstracts of this project.
     *
     * @param abstracts the abstracts of this project
     */
    public void setAbstracts(String abstracts);

    /**
     * Returns the element of this project.
     *
     * @return the element of this project
     */
    @AutoEscape
    public String getElement();

    /**
     * Sets the element of this project.
     *
     * @param element the element of this project
     */
    public void setElement(String element);

    /**
     * Returns the keywords of this project.
     *
     * @return the keywords of this project
     */
    @AutoEscape
    public String getKeywords();

    /**
     * Sets the keywords of this project.
     *
     * @param keywords the keywords of this project
     */
    public void setKeywords(String keywords);

    /**
     * Returns the website of this project.
     *
     * @return the website of this project
     */
    @AutoEscape
    public String getWebsite();

    /**
     * Sets the website of this project.
     *
     * @param website the website of this project
     */
    public void setWebsite(String website);

    /**
     * Returns the duration of this project.
     *
     * @return the duration of this project
     */
    @AutoEscape
    public String getDuration();

    /**
     * Sets the duration of this project.
     *
     * @param duration the duration of this project
     */
    public void setDuration(String duration);

    /**
     * Returns the rating of this project.
     *
     * @return the rating of this project
     */
    public long getRating();

    /**
     * Sets the rating of this project.
     *
     * @param rating the rating of this project
     */
    public void setRating(long rating);

    /**
     * Returns the importance of this project.
     *
     * @return the importance of this project
     */
    public long getImportance();

    /**
     * Sets the importance of this project.
     *
     * @param importance the importance of this project
     */
    public void setImportance(long importance);

    /**
     * Returns the specialtagging of this project.
     *
     * @return the specialtagging of this project
     */
    @AutoEscape
    public String getSpecialtagging();

    /**
     * Sets the specialtagging of this project.
     *
     * @param specialtagging the specialtagging of this project
     */
    public void setSpecialtagging(String specialtagging);

    /**
     * Returns the controlstatus of this project.
     *
     * @return the controlstatus of this project
     */
    public short getControlstatus();

    /**
     * Sets the controlstatus of this project.
     *
     * @param controlstatus the controlstatus of this project
     */
    public void setControlstatus(short controlstatus);

    /**
     * Returns the creator of this project.
     *
     * @return the creator of this project
     */
    @AutoEscape
    public String getCreator();

    /**
     * Sets the creator of this project.
     *
     * @param creator the creator of this project
     */
    public void setCreator(String creator);

    /**
     * Returns the creationdate of this project.
     *
     * @return the creationdate of this project
     */
    public Date getCreationdate();

    /**
     * Sets the creationdate of this project.
     *
     * @param creationdate the creationdate of this project
     */
    public void setCreationdate(Date creationdate);

    /**
     * Returns the moderator of this project.
     *
     * @return the moderator of this project
     */
    @AutoEscape
    public String getModerator();

    /**
     * Sets the moderator of this project.
     *
     * @param moderator the moderator of this project
     */
    public void setModerator(String moderator);

    /**
     * Returns the approvaldate of this project.
     *
     * @return the approvaldate of this project
     */
    public Date getApprovaldate();

    /**
     * Sets the approvaldate of this project.
     *
     * @param approvaldate the approvaldate of this project
     */
    public void setApprovaldate(Date approvaldate);

    /**
     * Returns the replaces ID of this project.
     *
     * @return the replaces ID of this project
     */
    public long getReplacesId();

    /**
     * Sets the replaces ID of this project.
     *
     * @param replacesId the replaces ID of this project
     */
    public void setReplacesId(long replacesId);

    /**
     * Returns the comments of this project.
     *
     * @return the comments of this project
     */
    @AutoEscape
    public String getComments();

    /**
     * Sets the comments of this project.
     *
     * @param comments the comments of this project
     */
    public void setComments(String comments);

    /**
     * Returns the textwebpage of this project.
     *
     * @return the textwebpage of this project
     */
    @AutoEscape
    public String getTextwebpage();

    /**
     * Sets the textwebpage of this project.
     *
     * @param textwebpage the textwebpage of this project
     */
    public void setTextwebpage(String textwebpage);

    /**
     * Returns the spatialvalues of this project.
     *
     * @return the spatialvalues of this project
     */
    @AutoEscape
    public String getSpatialvalues();

    /**
     * Sets the spatialvalues of this project.
     *
     * @param spatialvalues the spatialvalues of this project
     */
    public void setSpatialvalues(String spatialvalues);

    /**
     * Returns the source of this project.
     *
     * @return the source of this project
     */
    @AutoEscape
    public String getSource();

    /**
     * Sets the source of this project.
     *
     * @param source the source of this project
     */
    public void setSource(String source);

    /**
     * Returns the climateimpacts of this project.
     *
     * @return the climateimpacts of this project
     */
    @AutoEscape
    public String getClimateimpacts();

    /**
     * Sets the climateimpacts of this project.
     *
     * @param climateimpacts the climateimpacts of this project
     */
    public void setClimateimpacts(String climateimpacts);

    /**
     * Returns the lockdate of this project.
     *
     * @return the lockdate of this project
     */
    public Date getLockdate();

    /**
     * Sets the lockdate of this project.
     *
     * @param lockdate the lockdate of this project
     */
    public void setLockdate(Date lockdate);

    /**
     * Returns the feature of this project.
     *
     * @return the feature of this project
     */
    @AutoEscape
    public String getFeature();

    /**
     * Sets the feature of this project.
     *
     * @param feature the feature of this project
     */
    public void setFeature(String feature);

    /**
     * Returns the supdocs of this project.
     *
     * @return the supdocs of this project
     */
    @AutoEscape
    public String getSupdocs();

    /**
     * Sets the supdocs of this project.
     *
     * @param supdocs the supdocs of this project
     */
    public void setSupdocs(String supdocs);

    /**
     * Returns the geochars of this project.
     *
     * @return the geochars of this project
     */
    @AutoEscape
    public String getGeochars();

    /**
     * Sets the geochars of this project.
     *
     * @param geochars the geochars of this project
     */
    public void setGeochars(String geochars);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Project project);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Project> toCacheModel();

    @Override
    public Project toEscapedModel();

    @Override
    public Project toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
