create table Ace_AceItem (
	aceItemId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	wxsharvesterId LONG,
	cswharvesterId LONG,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	datatype VARCHAR(75) null,
	storedAt VARCHAR(75) null,
	storagetype VARCHAR(75) null,
	specialtagging VARCHAR(75) null,
	textSearch VARCHAR(75) null,
	keyword VARCHAR(75) null,
	targetresolution VARCHAR(75) null,
	spatialLayer VARCHAR(75) null,
	spatialValues VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	publicationDate DATE null,
	sectors_ VARCHAR(75) null,
	elements_ VARCHAR(75) null,
	climateimpacts_ VARCHAR(75) null,
	rating LONG,
	importance LONG,
	source VARCHAR(75) null,
	deeplink VARCHAR(75) null,
	controlstatus INTEGER,
	creator VARCHAR(75) null,
	creationdate DATE null,
	moderator VARCHAR(75) null,
	approvaldate DATE null,
	replacesId LONG,
	comments VARCHAR(75) null,
	textwebpage VARCHAR(75) null,
	year VARCHAR(75) null,
	geochars VARCHAR(75) null,
	feature VARCHAR(75) null,
	supdocs VARCHAR(75) null,
	admincomment VARCHAR(75) null,
	scenario VARCHAR(75) null,
	timeperiod VARCHAR(75) null,
	lockdate DATE null
);

create table Ace_CSWHarvester (
	cswharvesterid LONG not null primary key,
	name VARCHAR(75) null,
	url VARCHAR(75) null,
	freetext VARCHAR(75) null,
	title VARCHAR(75) null,
	abstrakt VARCHAR(75) null,
	subject VARCHAR(75) null,
	every INTEGER,
	topic VARCHAR(75) null,
	status VARCHAR(75) null,
	savedToGeoNetwork BOOLEAN,
	geonetworkId LONG,
	geonetworkUUID VARCHAR(75) null,
	companyId LONG,
	groupId LONG,
	type_ VARCHAR(75) null,
	username VARCHAR(75) null,
	password_ VARCHAR(75) null
);

create table Ace_WxsHarvester (
	wxsharvesterid LONG not null primary key,
	name VARCHAR(75) null,
	url VARCHAR(75) null,
	ogctype VARCHAR(75) null,
	every INTEGER,
	topic VARCHAR(75) null,
	status VARCHAR(75) null,
	savedToGeoNetwork BOOLEAN,
	geonetworkId LONG,
	geonetworkUUID VARCHAR(75) null,
	companyId LONG,
	groupId LONG
);